# **Data Cleaning Using Python module pandas**

In [1]:
# Import Required module 
import pyarrow 
import os 
import pandas as pd
import logging 
from tabulate import tabulate 


# Logger initializeation
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

logger = logging.getLogger(__name__)


#AWS authentication configuration
try: 
    os.environ["AWS_ACCESS_KEY"] = os.getenv("AWS_ACCESS_KEY")
    os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY")
    os.environ["AWS_DEFAULT_REGION"] = os.getenv("AWS_REGION")

    logger.info("AWS authentication configuration loaded successfully.")

except Exception as error:
    logger.exception(
        "Error occurred while loading AWS authentication configuration."
    )
    raise

2026-07-08 15:59:42,201 | INFO | AWS authentication configuration loaded successfully.

## **Customer Data Ingestion and Domain Segmentation**

In [2]:
# fetched  customer data from s3 bucket 
try:
    dfc = pd.read_csv("s3://ritsky-bucket-2025/retail_raw_dataset/raw_customers.csv")
    logger.info("Data fetched successfully from the S3 bucket.")

except Exception as error:
    logger.exception("Failed to fetch data from the S3 bucket.")


# count the total row and column of source dataset 
logger.info(
    f"Source dataset contains {dfc.shape[0]} records and {dfc.shape[1]} columns."
)


# breaking dataset using domain logic
customer_identity = [
    'customer_id',
    'title',
    'first_name', 
    'last_name', 
    'gender', 
    'is_active'
    ]
customer_address = [
    'customer_id', 
    'address', 
    'city', 
    'state', 
    'state_abbr', 
    'zip_code', 
    'country', 
    'region'
]
customer_content = [
    'customer_id', 
    'email', 
    'phone'
]
customer_business_info = [
    'customer_id',
    'customer_segment', 
    'loyalty_points',
    'preferred_channel', 
    'annual_income_usd', 
    'company' 
]
customer_dates = [
    'customer_id',
    'date_of_birth', 
    'account_created_date'
]


# Creating DataFrame for eatch domain 
try :
    customer_identity_df = dfc[customer_identity]
    customer_address_df = dfc[customer_address]
    customer_content_df = dfc[customer_content]
    customer_business_info_df = dfc[customer_business_info]
    customer_dates_df = dfc[customer_dates]

    logger.info("Customer domain DataFrames created successfully.")

    logger.info(f"customer_identity_df domain contains {customer_identity_df.shape[0]} record and {customer_identity_df.shape[1]} columns.")
    logger.info(f"customer_address_df domain contains {customer_address_df.shape[0]} record and {customer_address_df.shape[1]} columns.")
    logger.info(f"customer_content_df domain contains {customer_content_df.shape[0]} record and {customer_content_df.shape[1]} columns.")
    logger.info(f"customer_business_info_df domain contains {customer_business_info_df.shape[0]} record and {customer_business_info_df.shape[1]} columns.")
    logger.info(f"customer_dates_df domain contains {customer_dates_df.shape[0]} record and {customer_dates_df.shape[1]} columns.")

except Exception as error : 
    logger.exception("Failed to create customer domain DataFrames.")
    raise


required_columns = (
    customer_identity
    + customer_address
    + customer_content
    + customer_business_info
    + customer_dates
)

missing_columns = set(required_columns) - set(dfc.columns)

if missing_columns:
    raise ValueError(
        f"Missing required columns: {sorted(missing_columns)}"
    )
else : 
    logger.info("All DataFrame column match to required_columns.")

2026-07-08 15:59:47,193 | INFO | Found credentials in shared credentials file: ~/.aws/credentials
2026-07-08 15:59:48,200 | INFO | Data fetched successfully from the S3 bucket.
2026-07-08 15:59:48,202 | INFO | Source dataset contains 640 records and 25 columns.
2026-07-08 15:59:48,220 | INFO | Customer domain DataFrames created successfully.
2026-07-08 15:59:48,222 | INFO | customer_identity_df domain contains 640 record and 6 columns.
2026-07-08 15:59:48,223 | INFO | customer_address_df domain contains 640 record and 8 columns.
2026-07-08 15:59:48,224 | INFO | customer_content_df domain contains 640 record and 3 columns.
2026-07-08 15:59:48,225 | INFO | customer_business_info_df domain contains 640 record and 6 columns.
2026-07-08 15:59:48,226 | INFO | customer_dates_df domain contains 640 record and 3 columns.
2026-07-08 15:59:48,228 | INFO | All DataFrame column match to required_columns.

In [6]:
# fetched  employees data from s3 bucket 
try:
    dfe = pd.read_csv("s3://ritsky-bucket-2025/retail_raw_dataset/raw_employees.csv")
    logger.info("Data fetched successfully from the S3 bucket.")

except Exception as error:
    logger.exception("Failed to fetch data from the S3 bucket.")


# count the total row and column of source dataset 
logger.info(
    f"Source dataset contains {dfe.shape[0]} records and {dfe.shape[1]} columns."
)

# Employee Core Identity
employee_identity = [
    'employee_id',
    'first_name',
    'last_name',
    'full_name',
    'is_active'
]

# Employee Contact Information
employee_contact = [
    'employee_id',
    'email',
    'phone'
]

# Employee Job Information
employee_job_info = [
    'employee_id',
    'job_title',
    'department',
    'hire_date',
    'years_employed',
    'manager_id'
]

# Employee Compensation Information
employee_compensation = [
    'employee_id',
    'annual_salary_usd',
    'commission_rate_pct'
]

# Employee Performance Information
employee_performance = [
    'employee_id',
    'performance_rating'
]

# Employee Store Assignment
employee_store_assignment = [
    'employee_id',
    'store_id',
    'store_name',
    'store_city'
]

employee_identity_df = dfe[employee_identity]
employee_contact_df = dfe[employee_contact]
employee_job_info_df = dfe[employee_job_info]
employee_compensation_df = dfe[employee_compensation]
employee_performance_df = dfe[employee_performance]
employee_store_assignment_df = dfe[employee_store_assignment]

required_columns = (
    employee_identity
    + employee_contact
    + employee_job_info
    + employee_compensation
    + employee_performance
    + employee_store_assignment
)

missing_columns = set(required_columns) - set(dfe.columns)

if missing_columns:
    raise ValueError(
        f"Missing required columns: {sorted(missing_columns)}"
    )

2026-07-08 16:00:41,675 | INFO | Data fetched successfully from the S3 bucket.
2026-07-08 16:00:41,676 | INFO | Source dataset contains 100 records and 18 columns.

#### **Handling Missing Values**

In [2]:
# .isnull is the boolean data frame it's return output in form of true and false 
customer_business_info_df.isnull().head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,False,False,False,False,False,True
1,False,False,False,False,False,False
2,False,False,False,False,False,True
3,False,False,False,False,False,True
4,False,False,False,False,False,True

In [30]:
# .isna is the alias of .isnull both doing same work 
customer_business_info_df.isna().head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,False,False,False,False,False,True
1,False,False,False,False,False,False
2,False,False,False,False,False,True
3,False,False,False,False,False,True
4,False,False,False,False,False,True

In [36]:
customer_business_info_df.notna().head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,True,True,True,True,True,False
1,True,True,True,True,True,True
2,True,True,True,True,True,False
3,True,True,True,True,True,False
4,True,True,True,True,True,False

#### **Drop null values**

In [7]:
business_info_df = customer_business_info_df

In [8]:
# drop rows with ANY NaN
business_info_df.dropna().head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
6,1138,Platinum,9893.0,in-store,93485.0,Alpha Central Corp
8,1342,Gold,14633.0,ONLINE,207173.0,Alpha Pacific Co
13,1387,Gold,9550.0,Mobile,242653.0,Prime Prime Associates
25,9488,Silver,7775.0,catalog,245018.0,Future Elite Industries

In [45]:
# drop columns with ANY NaN
business_info_df.dropna(axis=1).head()

   customer_id customer_segment preferred_channel
0         1099           Silver            ONLINE
1         1170           Silver          In-Store
2         1457         Platinum           Catalog
3         1449           Bronze          IN STORE
4         1081           Bronze            mobile

In [47]:
# drop rows where ALL values are NaN 
business_info_df.dropna(how='all').head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,NaN
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,NaN
3,1449,Bronze,7108.0,IN STORE,231000.0,NaN
4,1081,Bronze,6602.0,mobile,206014.0,NaN

In [49]:
business_info_df.dropna(subset=['loyalty_points', 'company']).head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
6,1138,Platinum,9893.0,in-store,93485.0,Alpha Central Corp
8,1342,Gold,14633.0,ONLINE,207173.0,Alpha Pacific Co
13,1387,Gold,9550.0,Mobile,242653.0,Prime Prime Associates
25,9488,Silver,7775.0,catalog,245018.0,Future Elite Industries

In [51]:
# keep rows with at least 3 non-NaN
business_info_df.dropna(thresh=3).head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,NaN
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,NaN
3,1449,Bronze,7108.0,IN STORE,231000.0,NaN
4,1081,Bronze,6602.0,mobile,206014.0,NaN

#### **Fill null value**

In [53]:
# Fill all null value with 0 
business_info_df.fillna(0).head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,0
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,0
3,1449,Bronze,7108.0,IN STORE,231000.0,0
4,1081,Bronze,6602.0,mobile,206014.0,0

In [55]:
# column-specific filling null value 
business_info_df.fillna(
    {
        'loyalty_points' : 0.0 , 
        'company'        : 'Unknown'
    }
).head(10)

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,Unknown
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,Unknown
3,1449,Bronze,7108.0,IN STORE,231000.0,Unknown
4,1081,Bronze,6602.0,mobile,206014.0,Unknown
5,1247,Silver,4816.0,Catalog,160952.0,Unknown
6,1138,Platinum,9893.0,in-store,93485.0,Alpha Central Corp
7,1517,Platinum,12737.0,In-Store,149325.0,Unknown
8,1342,Gold,14633.0,ONLINE,207173.0,Alpha Pacific Co
9,1597,Bronze,9899.0,Online,73183.0,Unknown

In [63]:
# relpacing null value in loyalty_point with mean 
business_info_df.fillna(
    {
        'loyalty_points' : business_info_df['loyalty_points'].mean(),
        'company' : 'Unknown'
    }
).head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,Unknown
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,Unknown
3,1449,Bronze,7108.0,IN STORE,231000.0,Unknown
4,1081,Bronze,6602.0,mobile,206014.0,Unknown

In [64]:
# relpacing null value in loyalty_point with median 
business_info_df.fillna(
    {
        'loyalty_points' : business_info_df['loyalty_points'].median(),
        'company' : 'Unknown'
    }
).head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,Unknown
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,Unknown
3,1449,Bronze,7108.0,IN STORE,231000.0,Unknown
4,1081,Bronze,6602.0,mobile,206014.0,Unknown

In [67]:
# forward fill rows 
business_info_df['company'].fillna(method='ffill').head()

/tmp/ipykernel_8224/2482260931.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  business_info_df['company'].fillna(method='ffill').head()

0                 NaN
1    Horizon Red Corp
2    Horizon Red Corp
3    Horizon Red Corp
4    Horizon Red Corp
Name: company, dtype: object

In [70]:
# forward full using pandas method ffill
business_info_df['company'].ffill().sample(10)

111        Gold Prime Associates
356           Pacific Pacific Co
484    Horizon National Holdings
74             Global United Inc
131       Metro Prime Associates
116         Summit Gold Holdings
129       Metro Prime Associates
392         Metro Red Associates
196             Summit Metro Inc
151        Apex Pacific Partners
Name: company, dtype: object

In [72]:
# max 2 consecutive fills
business_info_df.fillna(method='pad', limit=2).head()

/tmp/ipykernel_8224/1108205805.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  business_info_df.fillna(method='pad', limit=2).head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,NaN
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,Horizon Red Corp
3,1449,Bronze,7108.0,IN STORE,231000.0,Horizon Red Corp
4,1081,Bronze,6602.0,mobile,206014.0,NaN

In [19]:
# backward fill
business_info_df['company'].bfill().sample(10)

219          Gold Alpha Group
112    National Next Partners
296           Smart Metro Inc
155             Red Gold Corp
558            Apex Summit Co
444        Next Blue Services
392             Red Smart LLC
236      Future Horizon Group
575           Summit Metro Co
162             Red Gold Corp
Name: company, dtype: object

##### **Interpolate**

In [ ]:
# Handling Missing Values Using Linear Interpolation
business_info_df['loyalty_points'].interpolate(method='linear').head()

0    7296.0
1    5841.0
2    3458.0
3    7108.0
4    6602.0
Name: loyalty_points, dtype: float64

In [ ]:
# Handling Time-Series Missing Values Using Time Interpolation
import numpy as np
df = pd.DataFrame(
    {
        "sales": [100, np.nan, 160]
    },
    index=pd.to_datetime(
        ["2025-01-01",
         "2025-01-02",
         "2025-01-05"]
    )
)

df.interpolate(method="time")

            sales
2025-01-01  100.0
2025-01-02  115.0
2025-01-05  160.0

In [ ]:
# Curve-Based Missing Value Imputation Using Polynomial Interpolation
import pandas as pd
import numpy as np

speed = pd.Series([
    0,
    10,
    np.nan,
    np.nan,
    80
])

print(speed.interpolate(method="linear"))

0     0.000000
1    10.000000
2    33.333333
3    56.666667
4    80.000000
dtype: float64

### **Replace specific values**

In [30]:
business_info_df.replace(pd.NA, -1).head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,-1
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,-1
3,1449,Bronze,7108.0,IN STORE,231000.0,-1
4,1081,Bronze,6602.0,mobile,206014.0,-1

In [36]:
customer_identity_df["is_active"].nunique()

10

In [35]:
customer_identity_df["is_active"].unique()

array(['Yes', 'FALSE', '0', 'N', '1', 'Y', 'No', 'TRUE', 'Inactive',
       'Active'], dtype=object)

In [37]:
customer_identity_df['is_active'].value_counts()

is_active
0           93
FALSE       83
1           76
No          75
Yes         74
N           74
TRUE        70
Y           69
Inactive    16
Active      10
Name: count, dtype: int64

In [41]:
customer_identity_df.replace(
    {
        'is_active' : {
            '0'        : False,
            'FALSE'    : False,
            '1'        : True,
            'No'       : False,
            'Yes'      : True,
            'N'        : False,
            'TRUE'     : True,
            'Y'        : True,
            'Inactive' : False ,
            'Active'   : True
        }
    }
).infer_objects(copy=False).head()

   customer_id  title first_name  last_name             gender  is_active
0         1099    NaN   Nicholas     Nelson  Prefer not to say       True
1         1170  Prof.     Thomas     Murphy         Non-Binary      False
2         1457    NaN    Stephen       king               male      False
3         1449    Dr.   Jennifer    Roberts             FEMALE      False
4         1081   Mrs.  Catherine  Rodriguez         non-binary      False

In [ ]:
# it is use to replace group of value with null value
# df.replace([0, -1], np.nan)

In [ ]:
# it is use to replace whitespace-only values with NaN
# df['col'].replace(r'^\s*$', np.nan, regex=True)

### **Handling Duplicates**

In [14]:
# Checks for exact duplicate rows across all columns.
# Returns True for duplicate rows and False otherwise.
business_info_df.duplicated().head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [21]:
# besd no subset 
business_info_df.duplicated(subset=['company']).head(10)

0    False
1    False
2     True
3     True
4     True
5     True
6    False
7     True
8    False
9     True
dtype: bool

In [23]:
# Mark all duplicate rows except the first occurrence
business_info_df.duplicated(keep='first').head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [28]:
business_info_df.duplicated(keep='last').head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [26]:
 # mark all duplicates (incl. first)
business_info_df.duplicated(keep=False).head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

### **Drop Duplicate Values**

In [30]:
# It dropt second row it two row return same value 
business_info_df.drop_duplicates().head()

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,NaN
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,NaN
3,1449,Bronze,7108.0,IN STORE,231000.0,NaN
4,1081,Bronze,6602.0,mobile,206014.0,NaN

In [31]:
# it drop anathor customer_id row if it any duplicate are in customer_id
business_info_df.drop_duplicates(subset=['customer_segment'])

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,NaN
2,1457,Platinum,3458.0,Catalog,234384.0,NaN
3,1449,Bronze,7108.0,IN STORE,231000.0,NaN
8,1342,Gold,14633.0,ONLINE,207173.0,Alpha Pacific Co

In [33]:
# it drop old data and return most recent data 
business_info_df.drop_duplicates(keep='last').head(10)

,customer_id,customer_segment,loyalty_points,preferred_channel,annual_income_usd,company
0,1099,Silver,7296.0,ONLINE,245670.0,NaN
1,1170,Silver,5841.0,In-Store,57415.0,Horizon Red Corp
2,1457,Platinum,3458.0,Catalog,234384.0,NaN
3,1449,Bronze,7108.0,IN STORE,231000.0,NaN
4,1081,Bronze,6602.0,mobile,206014.0,NaN
5,1247,Silver,4816.0,Catalog,160952.0,NaN
6,1138,Platinum,9893.0,in-store,93485.0,Alpha Central Corp
7,1517,Platinum,12737.0,In-Store,149325.0,NaN
8,1342,Gold,14633.0,ONLINE,207173.0,Alpha Pacific Co
9,1597,Bronze,9899.0,Online,73183.0,NaN

In [ ]:
# modify in-place (use carefully) and Remove Exact Duplicate Rows
business_info_df.drop_duplicates(inplace=True)

/tmp/ipykernel_136084/302768034.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  business_info_df.drop_duplicates(inplace=True)