In [1]:
# Mount google drive for extracting row data 
from google.colab import drive
drive.mount('/content/drive')

print("Google drive mounted successfully ")

Mounted at /content/drive
Google drive mounted successfully

In [3]:
!ls /content/drive/MyDrive/raw_dataset/retail_dataset

raw_customers.csv	     raw_products.csv  raw_sales_transactions.csv
raw_employees.csv	     raw_returns.csv   raw_stores.csv
raw_inventory_snapshots.csv  raw_reviews.csv

In [2]:
import pandas as pd 
from tabulate import tabulate

In [4]:
df = pd.read_csv("/content/drive/MyDrive/raw_dataset/retail_dataset/raw_customers.csv")

In [9]:
pd.set_option('display.max_colwidth', None)

In [5]:
customer_identity = ['customer_id', 'title', 'first_name', 'last_name', 'full_name', 'gender', 'is_active']
customer_address = ['customer_id', 'address', 'city', 'state', 'state_abbr', 'state_full', 'zip_code', 'country', 'region']
customer_content = ['customer_id', 'email', 'phone']
customer_business_info = ['customer_id','customer_segment', 'loyalty_points','preferred_channel', 'annual_income_usd', 'company' ]
customer_dates = ['customer_id','date_of_birth', 'age', 'account_created_date']

In [6]:
customer_identity_df = df[customer_identity]
customer_address_df = df[customer_address]
customer_content_df = df[customer_content]
customer_business_info_df = df[customer_business_info]
customer_dates_df = df[customer_dates]

In [7]:
# checking the top 5 row in dataset 
print(tabulate(customer_identity_df.head(), headers='keys', tablefmt='simple_grid'))

┌────┬───────────────┬─────────┬──────────────┬─────────────┬──────────────────────────┬───────────────────┬─────────────┐
│    │   customer_id │ title   │ first_name   │ last_name   │ full_name                │ gender            │ is_active   │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼───────────────────┼─────────────┤
│  0 │          1099 │ nan     │ Nicholas     │ Nelson      │ Nicholas Nelson          │ Prefer not to say │ Yes         │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼───────────────────┼─────────────┤
│  1 │          1170 │ Prof.   │ Thomas       │ Murphy      │ Prof. Thomas Murphy      │ Non-Binary        │ FALSE       │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼───────────────────┼─────────────┤
│  2 │          1457 │ nan     │ Stephen      │ king        │ Stephen King             │ male              │ 0           │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼───────────────────┼─────────────┤
│  3 │          1449 │ Dr.     │ Jennifer     │ Roberts     │ Dr. Jennifer Roberts     │ FEMALE            │ N           │
├────┼───────────────┼─────────┼──────────────┼─────────────┼──────────────────────────┼───────────────────┼─────────────┤
│  4 │          1081 │ Mrs.    │ Catherine    │ Rodriguez   │ Mrs. Catherine Rodriguez │ non-binary        │ 0           │
└────┴───────────────┴─────────┴──────────────┴─────────────┴──────────────────────────┴───────────────────┴─────────────┘

In [20]:
# checking the 10 random row for data sample 
df[['customer_id', 'address', 'city', 'state', 'state_abbr', 'state_full', 'zip_code', 'country', 'region']].sample(10)

,customer_id,address,city,state,state_abbr,state_full,zip_code,country,region
80,1261,7435 Cedar Blvd Apt 3,Denver,Colorado,CO,Colorado,45428,United States,West
68,1051,1849 Oak Ave,Las Vegas,NV,NV,Nevada,64950,USA,West
475,1476,2652 Sunset Dr,AUSTIN,Texas,TX,Texas,90733,US,South
120,1087,4191 Union St,Denver,CO,CO,Colorado,87846,USA,West
126,1483,5436 Park Ave Apt 41,Seattle,Washington,WA,Washington,94871,United States,West
66,1330,6755 School Rd,Minneapolis,Minnesota,MN,Minnesota,38607,U.S.A,Midwest
493,1111,1688 Cedar Blvd Apt 31,Austin,TX,TX,Texas,81884,USA,South
534,1008,5465 Elm St,New York,New York,NY,New York,44335,US,Northeast
24,1191,9477 College Ave,Tucson,AZ,AZ,Arizona,90753,United States,West
402,1186,8012 Valley Rd,Cleveland,Ohio,OH,Ohio,95078,USA,Midwest

In [21]:
# checking the 2 percent random row 
df[['customer_id', 'address', 'city', 'state', 'state_abbr', 'state_full', 'zip_code', 'country', 'region']].sample(frac=0.02)

,customer_id,address,city,state,state_abbr,state_full,zip_code,country,region
85,1527,142 Cedar Blvd,MEMPHIS,Tennessee,TN,Tennessee,56224,U.S.A,South
527,9458,3614 Church St Apt 28,Dallas,TX,TX,Texas,73654,USA,South
577,1344,8226 Pine Rd,San Francisco,California,CA,California,84062,U.S.A,West
258,1501,641 School Rd Apt 15,BALTIMORE,MD,MD,Maryland,85246,U.S.A,Northeast
196,1495,6868 Main St Apt 9,Kansas City,Missouri,MO,Missouri,61891,US,Midwest
591,1253,5094 Commerce Dr,New York,NY,NY,New York,10845,U.S.A,Northeast
184,1226,7456 High St,Milwaukee,WI,WI,Wisconsin,23137,US,Midwest
463,1193,3429 Commerce Dr Apt 31,Phoenix,AZ,AZ,Arizona,96966,USA,West
518,1327,1362 Forest Ln,Raleigh,North Carolina,NC,North Carolina,74847,USA,South
585,1290,9352 Hill Rd Apt 11,Denver,Colorado,CO,Colorado,62575,U.S.A,West
11,1076,2321 Cedar Blvd,Colorado Springs,CO,CO,Colorado,57826,USA,West
159,1284,6132 Main St,dallas,Texas,TX,Texas,55182,USA,South
631,1529,5800 Main St Apt 21,CHARLOTTE,NC,NC,North Carolina,39919,U.S.A,South

In [22]:
# checking the bottom 5 row 
print(tabulate(customer_business_info_df.tail(5), headers='keys', tablefmt='simple_grid'))

┌─────┬───────────────┬────────────────────┬──────────────────┬─────────────────────┬─────────────────────┬───────────────┐
│     │   customer_id │ customer_segment   │   loyalty_points │ preferred_channel   │   annual_income_usd │ company       │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────┤
│ 635 │          1447 │ Platinum           │             5643 │ APP                 │              129302 │ nan           │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────┤
│ 636 │          1106 │ Platinum           │             5693 │ Online              │               93447 │ nan           │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────┤
│ 637 │          1496 │ Platinum           │             2474 │ in-store            │               71519 │ nan           │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────┤
│ 638 │          1210 │ Platinum           │            12636 │ Store               │               52940 │ nan           │
├─────┼───────────────┼────────────────────┼──────────────────┼─────────────────────┼─────────────────────┼───────────────┤
│ 639 │          1573 │ Platinum           │            10938 │ IN STORE            │              206926 │ Metro Red Inc │
└─────┴───────────────┴────────────────────┴──────────────────┴─────────────────────┴─────────────────────┴───────────────┘

In [55]:
# checking the shape of dataset 
df.shape

(640, 25)

In [57]:
# checking the size of dataset 
df.size

16000

In [40]:
# checking the data type of dataset 
print(df.dtypes)

customer_id               int64
title                    object
first_name               object
last_name                object
full_name                object
gender                   object
date_of_birth            object
age                       int64
email                    object
phone                    object
address                  object
city                     object
state                    object
state_abbr               object
state_full               object
zip_code                  int64
country                  object
region                   object
customer_segment         object
loyalty_points          float64
is_active                object
account_created_date     object
preferred_channel        object
annual_income_usd       float64
company                  object
dtype: object

In [59]:
# checking the indexing of dataset 
df.index

RangeIndex(start=0, stop=640, step=1)

In [41]:
# checking the 1st to 3rd index of dataset \

df.values[0]

array([1099, nan, 'Nicholas', 'Nelson', 'Nicholas Nelson',
       'Prefer not to say', '05-09-1968', 56,
       'nicholas_nelson@icloud.com', '957.856.8145', '2201 Mill Rd',
       '  Dallas ', 'Texas', 'TX', 'Texas', 72908, 'U.S.A', 'South',
       'Silver', 7296.0, 'Yes', 'Dec 21, 2019', 'ONLINE', 245670.0, nan],
      dtype=object)

In [39]:
# checking the information about customer table 
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           640 non-null    int64
 1   title                 282 non-null    object
 2   first_name            640 non-null    object
 3   last_name             640 non-null    object
 4   full_name             640 non-null    object
 5   gender                585 non-null    object
 6   date_of_birth         640 non-null    object
 7   age                   640 non-null    int64
 8   email                 612 non-null    object
 9   phone                 612 non-null    object
 10  address               640 non-null    object
 11  city                  640 non-null    object
 12  state                 640 non-null    object
 13  state_abbr            640 non-null    object
 14  state_full            640 non-null    object
 15  zip_code              640 non-null    int64
 16  country               640 non-null    object
 17  region                640 non-null    object
 18  customer_segment      640 non-null    object
 19  loyalty_points        581 non-null    float64
 20  is_active             640 non-null    object
 21  account_created_date  640 non-null    object
 22  preferred_channel     640 non-null    object
 23  annual_income_usd     546 non-null    float64
 24  company               192 non-null    object
dtypes: float64(2), int64(3), object(20)
memory usage: 125.1+ KB
None

In [25]:
# checking the memory use 
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           640 non-null    int64
 1   title                 282 non-null    object
 2   first_name            640 non-null    object
 3   last_name             640 non-null    object
 4   full_name             640 non-null    object
 5   gender                585 non-null    object
 6   date_of_birth         640 non-null    object
 7   age                   640 non-null    int64
 8   email                 612 non-null    object
 9   phone                 612 non-null    object
 10  address               640 non-null    object
 11  city                  640 non-null    object
 12  state                 640 non-null    object
 13  state_abbr            640 non-null    object
 14  state_full            640 non-null    object
 15  zip_code              640 non-null    int64
 16  country               640 non-null    object
 17  region                640 non-null    object
 18  customer_segment      640 non-null    object
 19  loyalty_points        581 non-null    float64
 20  is_active             640 non-null    object
 21  account_created_date  640 non-null    object
 22  preferred_channel     640 non-null    object
 23  annual_income_usd     546 non-null    float64
 24  company               192 non-null    object
dtypes: float64(2), int64(3), object(20)
memory usage: 723.9 KB

In [26]:
df.describe()

,customer_id,age,zip_code,loyalty_points,annual_income_usd
count,640.000000,640.000000,640.000000,581.000000,546.000000
mean,1814.968750,42.765625,55070.653125,7318.053356,143881.163004
std,2002.669888,12.423339,25902.742031,4494.641028,69080.503718
min,1001.000000,22.000000,10255.000000,19.000000,25121.000000
25%,1160.750000,33.000000,32513.500000,3183.000000,76951.250000
50%,1320.500000,42.000000,55425.000000,7113.000000,147760.000000
75%,1480.250000,53.000000,76835.750000,11457.000000,207487.000000
max,9985.000000,65.000000,99674.000000,14977.000000,249877.000000

In [38]:
print(df.describe(include='all'))

        customer_id title first_name last_name   full_name  gender  \
count    640.000000   282        640       640         640     585
unique          NaN     5        212       205         591      13
top             NaN  Mrs.      Donna     James  Donna King  Female
freq            NaN    71         12        11           3      57
mean    1814.968750   NaN        NaN       NaN         NaN     NaN
std     2002.669888   NaN        NaN       NaN         NaN     NaN
min     1001.000000   NaN        NaN       NaN         NaN     NaN
25%     1160.750000   NaN        NaN       NaN         NaN     NaN
50%     1320.500000   NaN        NaN       NaN         NaN     NaN
75%     1480.250000   NaN        NaN       NaN         NaN     NaN
max     9985.000000   NaN        NaN       NaN         NaN     NaN

       date_of_birth         age                  email       phone  ...  \
count            640  640.000000                    612         612  ...
unique           598         NaN                    611         605  ...
top     May 08, 1968         NaN  brenda_adams@mail.com  6443188428  ...
freq               3         NaN                      2           2  ...
mean             NaN   42.765625                    NaN         NaN  ...
std              NaN   12.423339                    NaN         NaN  ...
min              NaN   22.000000                    NaN         NaN  ...
25%              NaN   33.000000                    NaN         NaN  ...
50%              NaN   42.000000                    NaN         NaN  ...
75%              NaN   53.000000                    NaN         NaN  ...
max              NaN   65.000000                    NaN         NaN  ...

            zip_code country region customer_segment loyalty_points  \
count     640.000000     640    640              640     581.000000
unique           NaN       4      4                4            NaN
top              NaN   U.S.A  South           Silver            NaN
freq             NaN     168    233              230            NaN
mean    55070.653125     NaN    NaN              NaN    7318.053356
std     25902.742031     NaN    NaN              NaN    4494.641028
min     10255.000000     NaN    NaN              NaN      19.000000
25%     32513.500000     NaN    NaN              NaN    3183.000000
50%     55425.000000     NaN    NaN              NaN    7113.000000
75%     76835.750000     NaN    NaN              NaN   11457.000000
max     99674.000000     NaN    NaN              NaN   14977.000000

        is_active account_created_date preferred_channel annual_income_usd  \
count         640                  640               640        546.000000
unique         10                  588                17               NaN
top             0           2021/11/10          In-Store               NaN
freq           93                    3                52               NaN
mean          NaN                  NaN               NaN     143881.163004
std           NaN                  NaN               NaN      69080.503718
min           NaN                  NaN               NaN      25121.000000
25%           NaN                  NaN               NaN      76951.250000
50%           NaN                  NaN               NaN     147760.000000
75%           NaN                  NaN               NaN     207487.000000
max           NaN                  NaN               NaN     249877.000000

                       company
count                      192
unique                     180
top     Prime Prime Associates
freq                         2
mean                       NaN
std                        NaN
min                        NaN
25%                        NaN
50%                        NaN
75%                        NaN
max                        NaN

[11 rows x 25 columns]

In [28]:
df.columns.tolist()

['customer_id',
 'title',
 'first_name',
 'last_name',
 'full_name',
 'gender',
 'date_of_birth',
 'age',
 'email',
 'phone',
 'address',
 'city',
 'state',
 'state_abbr',
 'state_full',
 'zip_code',
 'country',
 'region',
 'customer_segment',
 'loyalty_points',
 'is_active',
 'account_created_date',
 'preferred_channel',
 'annual_income_usd',
 'company']

In [32]:
# checking the length of the dataset 
len(df)

640

In [37]:
print(df.nunique())

customer_id             640
title                     5
first_name              212
last_name               205
full_name               591
gender                   13
date_of_birth           598
age                      44
email                   611
phone                   605
address                 600
city                    151
state                    80
state_abbr               25
state_full               25
zip_code                598
country                   4
region                    4
customer_segment          4
loyalty_points          533
is_active                10
account_created_date    588
preferred_channel        17
annual_income_usd       513
company                 180
dtype: int64

In [36]:
print(df.isnull().sum())

customer_id               0
title                   358
first_name                0
last_name                 0
full_name                 0
gender                   55
date_of_birth             0
age                       0
email                    28
phone                    28
address                   0
city                      0
state                     0
state_abbr                0
state_full                0
zip_code                  0
country                   0
region                    0
customer_segment          0
loyalty_points           59
is_active                 0
account_created_date      0
preferred_channel         0
annual_income_usd        94
company                 448
dtype: int64

In [45]:
print(df.isnull().sum() / len(df))

customer_id             0.000000
title                   0.559375
first_name              0.000000
last_name               0.000000
full_name               0.000000
gender                  0.085938
date_of_birth           0.000000
age                     0.000000
email                   0.043750
phone                   0.043750
address                 0.000000
city                    0.000000
state                   0.000000
state_abbr              0.000000
state_full              0.000000
zip_code                0.000000
country                 0.000000
region                  0.000000
customer_segment        0.000000
loyalty_points          0.092188
is_active               0.000000
account_created_date    0.000000
preferred_channel       0.000000
annual_income_usd       0.146875
company                 0.700000
dtype: float64

In [47]:
print(df.notnull().all())

customer_id              True
title                   False
first_name               True
last_name                True
full_name                True
gender                  False
date_of_birth            True
age                      True
email                   False
phone                   False
address                  True
city                     True
state                    True
state_abbr               True
state_full               True
zip_code                 True
country                  True
region                   True
customer_segment         True
loyalty_points          False
is_active                True
account_created_date     True
preferred_channel        True
annual_income_usd       False
company                 False
dtype: bool

In [54]:
print(df.apply(lambda col: col.duplicated().sum()))

customer_id               0
title                   634
first_name              428
last_name               435
full_name                49
gender                  626
date_of_birth            42
age                     596
email                    28
phone                    34
address                  40
city                    489
state                   560
state_abbr              615
state_full              615
zip_code                 42
country                 636
region                  636
customer_segment        636
loyalty_points          106
is_active               630
account_created_date     52
preferred_channel       623
annual_income_usd       126
company                 459
dtype: int64

In [55]:
df.duplicated(subset=['customer_id']).sum()

np.int64(0)

In [ ]:
# the summery of the datase
summery = pd.DataFrame({
    "data_type" : df.dtypes,
    "null_count": df.isnull().sum(),
    "null_percentage" : df.isnull().sum()/len(df),
    "not_null_count" : df.notnull().sum(),
    "unique_count" : df.nunique(),
    "duplicated_count" : df.apply(lambda col: col.duplicated().sum()),
    "null_like_values": df.apply(
    lambda col: col.astype(str).str.lower().isin(['null','none','n/a','na','']).sum()
    ),
    "memory_usage_mb": (df.memory_usage(deep=True)/1024**2).round(6)
})
print(tabulate(summery, headers='keys', tablefmt='simple_grid'))